//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiServiceEngine.Configuration
{
    
    
    /// <summary>
    /// The ApiSection Configuration Section.
    /// </summary>
    public partial class ApiSection : global::System.Configuration.ConfigurationSection
    {
        
        #region Singleton Instance
        /// <summary>
        /// The XML name of the ApiSection Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string ApiSectionSectionName = "api";
        
        /// <summary>
        /// The XML path of the ApiSection Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string ApiSectionSectionPath = "api";
        
        /// <summary>
        /// Gets the ApiSection instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public static global::ApiServiceEngine.Configuration.ApiSection Instance
        {
            get
            {
                return ((global::ApiServiceEngine.Configuration.ApiSection)(global::System.Configuration.ConfigurationManager.GetSection(global::ApiServiceEngine.Configuration.ApiSection.ApiSectionSectionPath)));
            }
        }
        #endregion
        
        #region Xmlns Property
        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string XmlnsPropertyName = "xmlns";
        
        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ApiServiceEngine.Configuration.ApiSection.XmlnsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::ApiServiceEngine.Configuration.ApiSection.XmlnsPropertyName]));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Tasks Property
        /// <summary>
        /// The XML name of the <see cref="Tasks"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string TasksPropertyName = "tasks";
        
        /// <summary>
        /// Gets or sets the Tasks.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        [global::System.ComponentModel.DescriptionAttribute("The Tasks.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ApiServiceEngine.Configuration.ApiSection.TasksPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::ApiServiceEngine.Configuration.Tasks Tasks
        {
            get
            {
                return ((global::ApiServiceEngine.Configuration.Tasks)(base[global::ApiServiceEngine.Configuration.ApiSection.TasksPropertyName]));
            }
            set
            {
                base[global::ApiServiceEngine.Configuration.ApiSection.TasksPropertyName] = value;
            }
        }
        #endregion
        
        #region Services Property
        /// <summary>
        /// The XML name of the <see cref="Services"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string ServicesPropertyName = "services";
        
        /// <summary>
        /// Gets or sets the Services.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        [global::System.ComponentModel.DescriptionAttribute("The Services.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ApiServiceEngine.Configuration.ApiSection.ServicesPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::ApiServiceEngine.Configuration.Services Services
        {
            get
            {
                return ((global::ApiServiceEngine.Configuration.Services)(base[global::ApiServiceEngine.Configuration.ApiSection.ServicesPropertyName]));
            }
            set
            {
                base[global::ApiServiceEngine.Configuration.ApiSection.ServicesPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace ApiServiceEngine.Configuration
{
    
    
    /// <summary>
    /// The RunMethod Configuration Element.
    /// </summary>
    public partial class RunMethod : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Method Property
        /// <summary>
        /// The XML name of the <see cref="Method"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string MethodPropertyName = "method";
        
        /// <summary>
        /// Gets or sets the Method.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        [global::System.ComponentModel.DescriptionAttribute("The Method.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ApiServiceEngine.Configuration.RunMethod.MethodPropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string Method
        {
            get
            {
                return ((string)(base[global::ApiServiceEngine.Configuration.RunMethod.MethodPropertyName]));
            }
            set
            {
                base[global::ApiServiceEngine.Configuration.RunMethod.MethodPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace ApiServiceEngine.Configuration
{
    
    
    /// <summary>
    /// A collection of RunMethod instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::ApiServiceEngine.Configuration.RunMethod), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMap, AddItemName="add", RemoveItemName="remove", ClearItemsName="clear")]
    public partial class RunMethods : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::ApiServiceEngine.Configuration.RunMethod"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string RunMethodPropertyName = "runMethod";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMap;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        protected override string ElementName
        {
            get
            {
                return global::ApiServiceEngine.Configuration.RunMethods.RunMethodPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::ApiServiceEngine.Configuration.RunMethods.RunMethodPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::ApiServiceEngine.Configuration.RunMethod)(element)).Method;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::ApiServiceEngine.Configuration.RunMethod"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::ApiServiceEngine.Configuration.RunMethod"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::ApiServiceEngine.Configuration.RunMethod();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::ApiServiceEngine.Configuration.RunMethod"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::ApiServiceEngine.Configuration.RunMethod"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public global::ApiServiceEngine.Configuration.RunMethod this[int index]
        {
            get
            {
                return ((global::ApiServiceEngine.Configuration.RunMethod)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::ApiServiceEngine.Configuration.RunMethod"/> with the specified key.
        /// </summary>
        /// <param name="method">The key of the <see cref="global::ApiServiceEngine.Configuration.RunMethod"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public global::ApiServiceEngine.Configuration.RunMethod this[object method]
        {
            get
            {
                return ((global::ApiServiceEngine.Configuration.RunMethod)(base.BaseGet(method)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::ApiServiceEngine.Configuration.RunMethod"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="runMethod">The <see cref="global::ApiServiceEngine.Configuration.RunMethod"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public void Add(global::ApiServiceEngine.Configuration.RunMethod runMethod)
        {
            base.BaseAdd(runMethod);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::ApiServiceEngine.Configuration.RunMethod"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="runMethod">The <see cref="global::ApiServiceEngine.Configuration.RunMethod"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public void Remove(global::ApiServiceEngine.Configuration.RunMethod runMethod)
        {
            base.BaseRemove(this.GetElementKey(runMethod));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::ApiServiceEngine.Configuration.RunMethod"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::ApiServiceEngine.Configuration.RunMethod"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public global::ApiServiceEngine.Configuration.RunMethod GetItemAt(int index)
        {
            return ((global::ApiServiceEngine.Configuration.RunMethod)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::ApiServiceEngine.Configuration.RunMethod"/> with the specified key.
        /// </summary>
        /// <param name="method">The key of the <see cref="global::ApiServiceEngine.Configuration.RunMethod"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public global::ApiServiceEngine.Configuration.RunMethod GetItemByKey(string method)
        {
            return ((global::ApiServiceEngine.Configuration.RunMethod)(base.BaseGet(((object)(method)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace ApiServiceEngine.Configuration
{
    
    
    /// <summary>
    /// The Task Configuration Element.
    /// </summary>
    public partial class Task : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Name Property
        /// <summary>
        /// The XML name of the <see cref="Name"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string NamePropertyName = "name";
        
        /// <summary>
        /// Gets or sets the Name.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        [global::System.ComponentModel.DescriptionAttribute("The Name.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ApiServiceEngine.Configuration.Task.NamePropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string Name
        {
            get
            {
                return ((string)(base[global::ApiServiceEngine.Configuration.Task.NamePropertyName]));
            }
            set
            {
                base[global::ApiServiceEngine.Configuration.Task.NamePropertyName] = value;
            }
        }
        #endregion
        
        #region Methods Property
        /// <summary>
        /// The XML name of the <see cref="Methods"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string MethodsPropertyName = "methods";
        
        /// <summary>
        /// Gets or sets the Methods.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        [global::System.ComponentModel.DescriptionAttribute("The Methods.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ApiServiceEngine.Configuration.Task.MethodsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::ApiServiceEngine.Configuration.RunMethods Methods
        {
            get
            {
                return ((global::ApiServiceEngine.Configuration.RunMethods)(base[global::ApiServiceEngine.Configuration.Task.MethodsPropertyName]));
            }
            set
            {
                base[global::ApiServiceEngine.Configuration.Task.MethodsPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace ApiServiceEngine.Configuration
{
    
    
    /// <summary>
    /// A collection of Task instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::ApiServiceEngine.Configuration.Task), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::ApiServiceEngine.Configuration.Tasks.TaskPropertyName)]
    public partial class Tasks : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::ApiServiceEngine.Configuration.Task"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string TaskPropertyName = "task";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        protected override string ElementName
        {
            get
            {
                return global::ApiServiceEngine.Configuration.Tasks.TaskPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::ApiServiceEngine.Configuration.Tasks.TaskPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::ApiServiceEngine.Configuration.Task)(element)).Name;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::ApiServiceEngine.Configuration.Task"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::ApiServiceEngine.Configuration.Task"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::ApiServiceEngine.Configuration.Task();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::ApiServiceEngine.Configuration.Task"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::ApiServiceEngine.Configuration.Task"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public global::ApiServiceEngine.Configuration.Task this[int index]
        {
            get
            {
                return ((global::ApiServiceEngine.Configuration.Task)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::ApiServiceEngine.Configuration.Task"/> with the specified key.
        /// </summary>
        /// <param name="name">The key of the <see cref="global::ApiServiceEngine.Configuration.Task"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public global::ApiServiceEngine.Configuration.Task this[object name]
        {
            get
            {
                return ((global::ApiServiceEngine.Configuration.Task)(base.BaseGet(name)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::ApiServiceEngine.Configuration.Task"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="task">The <see cref="global::ApiServiceEngine.Configuration.Task"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public void Add(global::ApiServiceEngine.Configuration.Task task)
        {
            base.BaseAdd(task);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::ApiServiceEngine.Configuration.Task"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="task">The <see cref="global::ApiServiceEngine.Configuration.Task"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public void Remove(global::ApiServiceEngine.Configuration.Task task)
        {
            base.BaseRemove(this.GetElementKey(task));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::ApiServiceEngine.Configuration.Task"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::ApiServiceEngine.Configuration.Task"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public global::ApiServiceEngine.Configuration.Task GetItemAt(int index)
        {
            return ((global::ApiServiceEngine.Configuration.Task)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::ApiServiceEngine.Configuration.Task"/> with the specified key.
        /// </summary>
        /// <param name="name">The key of the <see cref="global::ApiServiceEngine.Configuration.Task"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public global::ApiServiceEngine.Configuration.Task GetItemByKey(string name)
        {
            return ((global::ApiServiceEngine.Configuration.Task)(base.BaseGet(((object)(name)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace ApiServiceEngine.Configuration
{
    
    
    /// <summary>
    /// The Parameter Configuration Element.
    /// </summary>
    public partial class Parameter : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Name Property
        /// <summary>
        /// The XML name of the <see cref="Name"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string NamePropertyName = "name";
        
        /// <summary>
        /// Gets or sets the Name.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        [global::System.ComponentModel.DescriptionAttribute("The Name.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ApiServiceEngine.Configuration.Parameter.NamePropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string Name
        {
            get
            {
                return ((string)(base[global::ApiServiceEngine.Configuration.Parameter.NamePropertyName]));
            }
            set
            {
                base[global::ApiServiceEngine.Configuration.Parameter.NamePropertyName] = value;
            }
        }
        #endregion
        
        #region ApiName Property
        /// <summary>
        /// The XML name of the <see cref="ApiName"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string ApiNamePropertyName = "api_name";
        
        /// <summary>
        /// Gets or sets the ApiName.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        [global::System.ComponentModel.DescriptionAttribute("The ApiName.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ApiServiceEngine.Configuration.Parameter.ApiNamePropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual string ApiName
        {
            get
            {
                return ((string)(base[global::ApiServiceEngine.Configuration.Parameter.ApiNamePropertyName]));
            }
            set
            {
                base[global::ApiServiceEngine.Configuration.Parameter.ApiNamePropertyName] = value;
            }
        }
        #endregion
        
        #region IsPage Property
        /// <summary>
        /// The XML name of the <see cref="IsPage"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string IsPagePropertyName = "is_page";
        
        /// <summary>
        /// Gets or sets the IsPage.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        [global::System.ComponentModel.DescriptionAttribute("The IsPage.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ApiServiceEngine.Configuration.Parameter.IsPagePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false, DefaultValue=false)]
        public virtual bool IsPage
        {
            get
            {
                return ((bool)(base[global::ApiServiceEngine.Configuration.Parameter.IsPagePropertyName]));
            }
            set
            {
                base[global::ApiServiceEngine.Configuration.Parameter.IsPagePropertyName] = value;
            }
        }
        #endregion
        
        #region Index Property
        /// <summary>
        /// The XML name of the <see cref="Index"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string IndexPropertyName = "index";
        
        /// <summary>
        /// Gets or sets the Index.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        [global::System.ComponentModel.DescriptionAttribute("The Index.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ApiServiceEngine.Configuration.Parameter.IndexPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false, DefaultValue=0)]
        public virtual int Index
        {
            get
            {
                return ((int)(base[global::ApiServiceEngine.Configuration.Parameter.IndexPropertyName]));
            }
            set
            {
                base[global::ApiServiceEngine.Configuration.Parameter.IndexPropertyName] = value;
            }
        }
        #endregion
        
        #region Required Property
        /// <summary>
        /// The XML name of the <see cref="Required"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string RequiredPropertyName = "required";
        
        /// <summary>
        /// Gets or sets the Required.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        [global::System.ComponentModel.DescriptionAttribute("The Required.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ApiServiceEngine.Configuration.Parameter.RequiredPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false, DefaultValue=true)]
        public virtual bool Required
        {
            get
            {
                return ((bool)(base[global::ApiServiceEngine.Configuration.Parameter.RequiredPropertyName]));
            }
            set
            {
                base[global::ApiServiceEngine.Configuration.Parameter.RequiredPropertyName] = value;
            }
        }
        #endregion
        
        #region Db Property
        /// <summary>
        /// The XML name of the <see cref="Db"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string DbPropertyName = "db";
        
        /// <summary>
        /// Gets or sets the Db.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        [global::System.ComponentModel.DescriptionAttribute("The Db.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ApiServiceEngine.Configuration.Parameter.DbPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::ApiServiceEngine.Configuration.DbProperty Db
        {
            get
            {
                return ((global::ApiServiceEngine.Configuration.DbProperty)(base[global::ApiServiceEngine.Configuration.Parameter.DbPropertyName]));
            }
            set
            {
                base[global::ApiServiceEngine.Configuration.Parameter.DbPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace ApiServiceEngine.Configuration
{
    
    
    /// <summary>
    /// The DbProperty Configuration Element.
    /// </summary>
    public partial class DbProperty : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Field Property
        /// <summary>
        /// The XML name of the <see cref="Field"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string FieldPropertyName = "field";
        
        /// <summary>
        /// Gets or sets the Field.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        [global::System.ComponentModel.DescriptionAttribute("The Field.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ApiServiceEngine.Configuration.DbProperty.FieldPropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string Field
        {
            get
            {
                return ((string)(base[global::ApiServiceEngine.Configuration.DbProperty.FieldPropertyName]));
            }
            set
            {
                base[global::ApiServiceEngine.Configuration.DbProperty.FieldPropertyName] = value;
            }
        }
        #endregion
        
        #region Type Property
        /// <summary>
        /// The XML name of the <see cref="Type"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string TypePropertyName = "type";
        
        /// <summary>
        /// Gets or sets the Type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        [global::System.ComponentModel.DescriptionAttribute("The Type.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ApiServiceEngine.Configuration.DbProperty.TypePropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual global::FirebirdSql.Data.FirebirdClient.FbDbType Type
        {
            get
            {
                return ((global::FirebirdSql.Data.FirebirdClient.FbDbType)(base[global::ApiServiceEngine.Configuration.DbProperty.TypePropertyName]));
            }
            set
            {
                base[global::ApiServiceEngine.Configuration.DbProperty.TypePropertyName] = value;
            }
        }
        #endregion
        
        #region Length Property
        /// <summary>
        /// The XML name of the <see cref="Length"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string LengthPropertyName = "length";
        
        /// <summary>
        /// Gets or sets the Length.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        [global::System.ComponentModel.DescriptionAttribute("The Length.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ApiServiceEngine.Configuration.DbProperty.LengthPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual int Length
        {
            get
            {
                return ((int)(base[global::ApiServiceEngine.Configuration.DbProperty.LengthPropertyName]));
            }
            set
            {
                base[global::ApiServiceEngine.Configuration.DbProperty.LengthPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace ApiServiceEngine.Configuration
{
    
    
    /// <summary>
    /// A collection of Parameter instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::ApiServiceEngine.Configuration.Parameter), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::ApiServiceEngine.Configuration.Out.ParameterPropertyName)]
    public partial class Out : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::ApiServiceEngine.Configuration.Parameter"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string ParameterPropertyName = "parameter";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        protected override string ElementName
        {
            get
            {
                return global::ApiServiceEngine.Configuration.Out.ParameterPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::ApiServiceEngine.Configuration.Out.ParameterPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::ApiServiceEngine.Configuration.Parameter)(element)).Name;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::ApiServiceEngine.Configuration.Parameter"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::ApiServiceEngine.Configuration.Parameter"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::ApiServiceEngine.Configuration.Parameter();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::ApiServiceEngine.Configuration.Parameter"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::ApiServiceEngine.Configuration.Parameter"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public global::ApiServiceEngine.Configuration.Parameter this[int index]
        {
            get
            {
                return ((global::ApiServiceEngine.Configuration.Parameter)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::ApiServiceEngine.Configuration.Parameter"/> with the specified key.
        /// </summary>
        /// <param name="name">The key of the <see cref="global::ApiServiceEngine.Configuration.Parameter"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public global::ApiServiceEngine.Configuration.Parameter this[object name]
        {
            get
            {
                return ((global::ApiServiceEngine.Configuration.Parameter)(base.BaseGet(name)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::ApiServiceEngine.Configuration.Parameter"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="parameter">The <see cref="global::ApiServiceEngine.Configuration.Parameter"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public void Add(global::ApiServiceEngine.Configuration.Parameter parameter)
        {
            base.BaseAdd(parameter);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::ApiServiceEngine.Configuration.Parameter"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="parameter">The <see cref="global::ApiServiceEngine.Configuration.Parameter"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public void Remove(global::ApiServiceEngine.Configuration.Parameter parameter)
        {
            base.BaseRemove(this.GetElementKey(parameter));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::ApiServiceEngine.Configuration.Parameter"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::ApiServiceEngine.Configuration.Parameter"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public global::ApiServiceEngine.Configuration.Parameter GetItemAt(int index)
        {
            return ((global::ApiServiceEngine.Configuration.Parameter)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::ApiServiceEngine.Configuration.Parameter"/> with the specified key.
        /// </summary>
        /// <param name="name">The key of the <see cref="global::ApiServiceEngine.Configuration.Parameter"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public global::ApiServiceEngine.Configuration.Parameter GetItemByKey(string name)
        {
            return ((global::ApiServiceEngine.Configuration.Parameter)(base.BaseGet(((object)(name)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace ApiServiceEngine.Configuration
{
    
    
    /// <summary>
    /// A collection of Parameter instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::ApiServiceEngine.Configuration.Parameter), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::ApiServiceEngine.Configuration.In.ParameterPropertyName)]
    public partial class In : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::ApiServiceEngine.Configuration.Parameter"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string ParameterPropertyName = "parameter";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        protected override string ElementName
        {
            get
            {
                return global::ApiServiceEngine.Configuration.In.ParameterPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::ApiServiceEngine.Configuration.In.ParameterPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::ApiServiceEngine.Configuration.Parameter)(element)).Name;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::ApiServiceEngine.Configuration.Parameter"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::ApiServiceEngine.Configuration.Parameter"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::ApiServiceEngine.Configuration.Parameter();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::ApiServiceEngine.Configuration.Parameter"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::ApiServiceEngine.Configuration.Parameter"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public global::ApiServiceEngine.Configuration.Parameter this[int index]
        {
            get
            {
                return ((global::ApiServiceEngine.Configuration.Parameter)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::ApiServiceEngine.Configuration.Parameter"/> with the specified key.
        /// </summary>
        /// <param name="name">The key of the <see cref="global::ApiServiceEngine.Configuration.Parameter"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public global::ApiServiceEngine.Configuration.Parameter this[object name]
        {
            get
            {
                return ((global::ApiServiceEngine.Configuration.Parameter)(base.BaseGet(name)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::ApiServiceEngine.Configuration.Parameter"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="parameter">The <see cref="global::ApiServiceEngine.Configuration.Parameter"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public void Add(global::ApiServiceEngine.Configuration.Parameter parameter)
        {
            base.BaseAdd(parameter);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::ApiServiceEngine.Configuration.Parameter"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="parameter">The <see cref="global::ApiServiceEngine.Configuration.Parameter"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public void Remove(global::ApiServiceEngine.Configuration.Parameter parameter)
        {
            base.BaseRemove(this.GetElementKey(parameter));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::ApiServiceEngine.Configuration.Parameter"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::ApiServiceEngine.Configuration.Parameter"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public global::ApiServiceEngine.Configuration.Parameter GetItemAt(int index)
        {
            return ((global::ApiServiceEngine.Configuration.Parameter)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::ApiServiceEngine.Configuration.Parameter"/> with the specified key.
        /// </summary>
        /// <param name="name">The key of the <see cref="global::ApiServiceEngine.Configuration.Parameter"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public global::ApiServiceEngine.Configuration.Parameter GetItemByKey(string name)
        {
            return ((global::ApiServiceEngine.Configuration.Parameter)(base.BaseGet(((object)(name)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace ApiServiceEngine.Configuration
{
    
    
    /// <summary>
    /// The Method Configuration Element.
    /// </summary>
    public partial class Method : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Name Property
        /// <summary>
        /// The XML name of the <see cref="Name"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string NamePropertyName = "name";
        
        /// <summary>
        /// Gets or sets the Name.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        [global::System.ComponentModel.DescriptionAttribute("The Name.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ApiServiceEngine.Configuration.Method.NamePropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string Name
        {
            get
            {
                return ((string)(base[global::ApiServiceEngine.Configuration.Method.NamePropertyName]));
            }
            set
            {
                base[global::ApiServiceEngine.Configuration.Method.NamePropertyName] = value;
            }
        }
        #endregion
        
        #region ApiName Property
        /// <summary>
        /// The XML name of the <see cref="ApiName"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string ApiNamePropertyName = "apiName";
        
        /// <summary>
        /// Gets or sets the ApiName.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        [global::System.ComponentModel.DescriptionAttribute("The ApiName.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ApiServiceEngine.Configuration.Method.ApiNamePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string ApiName
        {
            get
            {
                return ((string)(base[global::ApiServiceEngine.Configuration.Method.ApiNamePropertyName]));
            }
            set
            {
                base[global::ApiServiceEngine.Configuration.Method.ApiNamePropertyName] = value;
            }
        }
        #endregion
        
        #region Procedure Property
        /// <summary>
        /// The XML name of the <see cref="Procedure"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string ProcedurePropertyName = "procedure";
        
        /// <summary>
        /// Gets or sets the Procedure.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        [global::System.ComponentModel.DescriptionAttribute("The Procedure.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ApiServiceEngine.Configuration.Method.ProcedurePropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Procedure
        {
            get
            {
                return ((string)(base[global::ApiServiceEngine.Configuration.Method.ProcedurePropertyName]));
            }
            set
            {
                base[global::ApiServiceEngine.Configuration.Method.ProcedurePropertyName] = value;
            }
        }
        #endregion
        
        #region In Property
        /// <summary>
        /// The XML name of the <see cref="In"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string InPropertyName = "in";
        
        /// <summary>
        /// Gets or sets the In.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        [global::System.ComponentModel.DescriptionAttribute("The In.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ApiServiceEngine.Configuration.Method.InPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::ApiServiceEngine.Configuration.In In
        {
            get
            {
                return ((global::ApiServiceEngine.Configuration.In)(base[global::ApiServiceEngine.Configuration.Method.InPropertyName]));
            }
            set
            {
                base[global::ApiServiceEngine.Configuration.Method.InPropertyName] = value;
            }
        }
        #endregion
        
        #region Out Property
        /// <summary>
        /// The XML name of the <see cref="Out"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string OutPropertyName = "out";
        
        /// <summary>
        /// Gets or sets the Out.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        [global::System.ComponentModel.DescriptionAttribute("The Out.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ApiServiceEngine.Configuration.Method.OutPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::ApiServiceEngine.Configuration.Out Out
        {
            get
            {
                return ((global::ApiServiceEngine.Configuration.Out)(base[global::ApiServiceEngine.Configuration.Method.OutPropertyName]));
            }
            set
            {
                base[global::ApiServiceEngine.Configuration.Method.OutPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace ApiServiceEngine.Configuration
{
    
    
    /// <summary>
    /// A collection of Method instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::ApiServiceEngine.Configuration.Method), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::ApiServiceEngine.Configuration.Methods.MethodPropertyName)]
    public partial class Methods : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::ApiServiceEngine.Configuration.Method"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string MethodPropertyName = "method";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        protected override string ElementName
        {
            get
            {
                return global::ApiServiceEngine.Configuration.Methods.MethodPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::ApiServiceEngine.Configuration.Methods.MethodPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::ApiServiceEngine.Configuration.Method)(element)).Name;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::ApiServiceEngine.Configuration.Method"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::ApiServiceEngine.Configuration.Method"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::ApiServiceEngine.Configuration.Method();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::ApiServiceEngine.Configuration.Method"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::ApiServiceEngine.Configuration.Method"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public global::ApiServiceEngine.Configuration.Method this[int index]
        {
            get
            {
                return ((global::ApiServiceEngine.Configuration.Method)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::ApiServiceEngine.Configuration.Method"/> with the specified key.
        /// </summary>
        /// <param name="name">The key of the <see cref="global::ApiServiceEngine.Configuration.Method"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public global::ApiServiceEngine.Configuration.Method this[object name]
        {
            get
            {
                return ((global::ApiServiceEngine.Configuration.Method)(base.BaseGet(name)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::ApiServiceEngine.Configuration.Method"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="method">The <see cref="global::ApiServiceEngine.Configuration.Method"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public void Add(global::ApiServiceEngine.Configuration.Method method)
        {
            base.BaseAdd(method);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::ApiServiceEngine.Configuration.Method"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="method">The <see cref="global::ApiServiceEngine.Configuration.Method"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public void Remove(global::ApiServiceEngine.Configuration.Method method)
        {
            base.BaseRemove(this.GetElementKey(method));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::ApiServiceEngine.Configuration.Method"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::ApiServiceEngine.Configuration.Method"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public global::ApiServiceEngine.Configuration.Method GetItemAt(int index)
        {
            return ((global::ApiServiceEngine.Configuration.Method)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::ApiServiceEngine.Configuration.Method"/> with the specified key.
        /// </summary>
        /// <param name="name">The key of the <see cref="global::ApiServiceEngine.Configuration.Method"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public global::ApiServiceEngine.Configuration.Method GetItemByKey(string name)
        {
            return ((global::ApiServiceEngine.Configuration.Method)(base.BaseGet(((object)(name)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace ApiServiceEngine.Configuration
{
    
    
    /// <summary>
    /// The Settings Configuration Element.
    /// </summary>
    public partial class Settings : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Url Property
        /// <summary>
        /// The XML name of the <see cref="Url"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string UrlPropertyName = "url";
        
        /// <summary>
        /// Gets or sets the Url.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        [global::System.ComponentModel.DescriptionAttribute("The Url.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ApiServiceEngine.Configuration.Settings.UrlPropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual string Url
        {
            get
            {
                return ((string)(base[global::ApiServiceEngine.Configuration.Settings.UrlPropertyName]));
            }
            set
            {
                base[global::ApiServiceEngine.Configuration.Settings.UrlPropertyName] = value;
            }
        }
        #endregion
        
        #region Login Property
        /// <summary>
        /// The XML name of the <see cref="Login"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string LoginPropertyName = "login";
        
        /// <summary>
        /// Gets or sets the Login.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        [global::System.ComponentModel.DescriptionAttribute("The Login.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ApiServiceEngine.Configuration.Settings.LoginPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Login
        {
            get
            {
                return ((string)(base[global::ApiServiceEngine.Configuration.Settings.LoginPropertyName]));
            }
            set
            {
                base[global::ApiServiceEngine.Configuration.Settings.LoginPropertyName] = value;
            }
        }
        #endregion
        
        #region Password Property
        /// <summary>
        /// The XML name of the <see cref="Password"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string PasswordPropertyName = "password";
        
        /// <summary>
        /// Gets or sets the Password.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        [global::System.ComponentModel.DescriptionAttribute("The Password.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ApiServiceEngine.Configuration.Settings.PasswordPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Password
        {
            get
            {
                return ((string)(base[global::ApiServiceEngine.Configuration.Settings.PasswordPropertyName]));
            }
            set
            {
                base[global::ApiServiceEngine.Configuration.Settings.PasswordPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace ApiServiceEngine.Configuration
{
    
    
    /// <summary>
    /// The Service Configuration Element.
    /// </summary>
    public partial class Service : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Name Property
        /// <summary>
        /// The XML name of the <see cref="Name"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string NamePropertyName = "name";
        
        /// <summary>
        /// Gets or sets the Name.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        [global::System.ComponentModel.DescriptionAttribute("The Name.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ApiServiceEngine.Configuration.Service.NamePropertyName, IsRequired=true, IsKey=true, IsDefaultCollection=false)]
        public virtual string Name
        {
            get
            {
                return ((string)(base[global::ApiServiceEngine.Configuration.Service.NamePropertyName]));
            }
            set
            {
                base[global::ApiServiceEngine.Configuration.Service.NamePropertyName] = value;
            }
        }
        #endregion
        
        #region Comment Property
        /// <summary>
        /// The XML name of the <see cref="Comment"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string CommentPropertyName = "comment";
        
        /// <summary>
        /// Gets or sets the Comment.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        [global::System.ComponentModel.DescriptionAttribute("The Comment.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ApiServiceEngine.Configuration.Service.CommentPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Comment
        {
            get
            {
                return ((string)(base[global::ApiServiceEngine.Configuration.Service.CommentPropertyName]));
            }
            set
            {
                base[global::ApiServiceEngine.Configuration.Service.CommentPropertyName] = value;
            }
        }
        #endregion
        
        #region Type Property
        /// <summary>
        /// The XML name of the <see cref="Type"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string TypePropertyName = "type";
        
        /// <summary>
        /// Gets or sets the Type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        [global::System.ComponentModel.DescriptionAttribute("The Type.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ApiServiceEngine.Configuration.Service.TypePropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual string Type
        {
            get
            {
                return ((string)(base[global::ApiServiceEngine.Configuration.Service.TypePropertyName]));
            }
            set
            {
                base[global::ApiServiceEngine.Configuration.Service.TypePropertyName] = value;
            }
        }
        #endregion
        
        #region Settings Property
        /// <summary>
        /// The XML name of the <see cref="Settings"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string SettingsPropertyName = "settings";
        
        /// <summary>
        /// Gets or sets the Settings.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        [global::System.ComponentModel.DescriptionAttribute("The Settings.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ApiServiceEngine.Configuration.Service.SettingsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::ApiServiceEngine.Configuration.Settings Settings
        {
            get
            {
                return ((global::ApiServiceEngine.Configuration.Settings)(base[global::ApiServiceEngine.Configuration.Service.SettingsPropertyName]));
            }
            set
            {
                base[global::ApiServiceEngine.Configuration.Service.SettingsPropertyName] = value;
            }
        }
        #endregion
        
        #region Methods Property
        /// <summary>
        /// The XML name of the <see cref="Methods"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string MethodsPropertyName = "methods";
        
        /// <summary>
        /// Gets or sets the Methods.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        [global::System.ComponentModel.DescriptionAttribute("The Methods.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::ApiServiceEngine.Configuration.Service.MethodsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual global::ApiServiceEngine.Configuration.Methods Methods
        {
            get
            {
                return ((global::ApiServiceEngine.Configuration.Methods)(base[global::ApiServiceEngine.Configuration.Service.MethodsPropertyName]));
            }
            set
            {
                base[global::ApiServiceEngine.Configuration.Service.MethodsPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace ApiServiceEngine.Configuration
{
    
    
    /// <summary>
    /// A collection of Service instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::ApiServiceEngine.Configuration.Service), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate, AddItemName=global::ApiServiceEngine.Configuration.Services.ServicePropertyName)]
    public partial class Services : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::ApiServiceEngine.Configuration.Service"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        internal const string ServicePropertyName = "service";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        protected override string ElementName
        {
            get
            {
                return global::ApiServiceEngine.Configuration.Services.ServicePropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::ApiServiceEngine.Configuration.Services.ServicePropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return ((global::ApiServiceEngine.Configuration.Service)(element)).Name;
        }
        
        /// <summary>
        /// Creates a new <see cref="global::ApiServiceEngine.Configuration.Service"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::ApiServiceEngine.Configuration.Service"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::ApiServiceEngine.Configuration.Service();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::ApiServiceEngine.Configuration.Service"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::ApiServiceEngine.Configuration.Service"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public global::ApiServiceEngine.Configuration.Service this[int index]
        {
            get
            {
                return ((global::ApiServiceEngine.Configuration.Service)(base.BaseGet(index)));
            }
        }
        
        /// <summary>
        /// Gets the <see cref="global::ApiServiceEngine.Configuration.Service"/> with the specified key.
        /// </summary>
        /// <param name="name">The key of the <see cref="global::ApiServiceEngine.Configuration.Service"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public global::ApiServiceEngine.Configuration.Service this[object name]
        {
            get
            {
                return ((global::ApiServiceEngine.Configuration.Service)(base.BaseGet(name)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::ApiServiceEngine.Configuration.Service"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="service">The <see cref="global::ApiServiceEngine.Configuration.Service"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public void Add(global::ApiServiceEngine.Configuration.Service service)
        {
            base.BaseAdd(service);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::ApiServiceEngine.Configuration.Service"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="service">The <see cref="global::ApiServiceEngine.Configuration.Service"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public void Remove(global::ApiServiceEngine.Configuration.Service service)
        {
            base.BaseRemove(this.GetElementKey(service));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::ApiServiceEngine.Configuration.Service"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::ApiServiceEngine.Configuration.Service"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public global::ApiServiceEngine.Configuration.Service GetItemAt(int index)
        {
            return ((global::ApiServiceEngine.Configuration.Service)(base.BaseGet(index)));
        }
        
        /// <summary>
        /// Gets the <see cref="global::ApiServiceEngine.Configuration.Service"/> with the specified key.
        /// </summary>
        /// <param name="name">The key of the <see cref="global::ApiServiceEngine.Configuration.Service"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public global::ApiServiceEngine.Configuration.Service GetItemByKey(string name)
        {
            return ((global::ApiServiceEngine.Configuration.Service)(base.BaseGet(((object)(name)))));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.3.2")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
